### ISSUE TITLE
Assign multiple limited diseases to users [5]

### ISSUE THREAD

**Issue by d1pen** [SORMAS-Foundation/SORMAS-Project#11435]
### Feature Description

![image](https://user-images.githubusercontent.com/32364062/216372083-fd396614-48c6-4a8e-b10b-f26e3a4341da.png)

Currently, users can be assigned a limited disease that will only allow them to see data related to this disease.

### Proposed Change

Allow users to be assigned multiple limited diseases, not only one.

### Added Value
In some countries, there is joint surveillance done on multiple diseases at the same time. Users tasked with this will be able to create and edit data related to all those diseases, but they don't need to have access to all other diseases that they don't work on.

### Acceptance Criteria

All changes have to be done in the web and mobile app.

- [x] The `User.limitedDisease` field has been renamed to `limitedDiseases` and its data type has been changed to a list of diseases
- [x] Existing data is properly migrated in `sormas_schema.sql` and `DatabaseHelper`
- [x] All code that checks access to data based on the user's limited disease now checks whether ANY of the limited diseases of the user applies; a possible approach would be to use `cb.like("%DISEASE%")` instead of `cb.equal`
- [x] In the user edit form in the web app, the limited disease field has been replaced with a new component:
  - Heading: "Disease restrictions"
  - Checkbox: "Restrict access to specific diseases"; automatically check this if the user has limited diseases; if checked, display the other elements described below
  - Explanation label: "Mark all diseases that the user is supposed to have access to"
  - Checkboxes for all active primary case-based diseases (i.e. all diseases that are currently in the dropdown) spread over three columns; if the `limitedDiseases` field of the user contains diseases that has been set to inactive, also add checkboxes for those; mark checkboxes based on the content of the `limitedDiseases` field
  - Saving the edit form updates the `limitedDiseases` field according to the checkbox values

### Implementation Details

In the web app database, store the limited diseases as a `text` data type, and write a new `DiseaseListConverter` similar to the `AgeGroupsConverter` used for disease configurations; in the mobile app, use the same pattern that we use for age groups as well, i.e. persist a `limitedDiseasesString` field, make the `limitedDiseases` field transient and use a conversion method to convert the String field to a list of diseases.

**Comment by adinaflorea9** [comment]
I am reopening the ticket so that 'if the limitedDiseases field of the user contains diseases that has been set to inactive, also add checkboxes for those;' can be implemented - currently if a disease is set as limited disease for the user, then the respective disease is set to inactive, the checkbox for it is no longer visible.

**Comment by adinaflorea9** [comment]
@leventegal-she The following should also be addressed:

When a user has at least 1 limited disease, or more, then their access to one of them is removed, the entities of that disease are not displayed as before to the user (as before the implementation of the current ticket).

Steps to reproduce:
1. For a default Surveillance Officer, assign two limiting diseases (Anthrax and Congenital Rubella);
2. Log in with the user and create at lease one case of Anthrax;
3. Log in with an Admin and edit the user (deselect Anthrax as limiting disease);
4. Search for the case created at step 2 and copy the URL;
5. Log in with the user from step 1 (that was edited at step 4) and paste the URL;
Actual behavior: The entity page is not displayed correctly and a waning appears.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/8bccacb1-c8e4-451c-8fee-3d1a39325f54)

Expected behavior: The user should be able to see the entity page via copied URL access, in read only mode, with pseudonymization done for the necessary fields (Just as the behavior was before for a user whole limited disease was changed from one value to another).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(37e2d69).
