### ISSUE TITLE
Add tasks to environments [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11780]
### Feature Description

For environments, a new task context and a few new task types are required. This issue is part of the EPIC https://github.com/hzi-braunschweig/SORMAS-Project/issues/11533 on the environmental surveillance module.

### Added Value/Benefit

To manage routine activities of the env entity.

### Acceptance Criteria

- [x] Add a new `ENVIRONMENT` task context, depending on the `ENVIRONMENT_VIEW` user right, that is connected to the `ENVIRONMENT_MANAGEMENT` feature type
- [x] Add the following task types (caption in brackets):
  - `ENVIRONMENT_INVESTIGATION` (Environment investigation)
  - `DECONTAMINATION_DISINFECTION` (Decontamination/disinfection activities)
- [x] Extend the scope of the `SAMPLE_COLLECTION` and `OTHER` task types to environments
- [x] Extend the tasks user filter to properly incorporate environment tasks
- [x] Add a tasks card to the right side of the environment edit form in the web app
- [x] Add a tasks section to the environment activity in the mobile app
- [x] Ensure that environment tasks are properly shown in environments and are synchronized to the mobile app if the user has access to them

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Is the task type enums configurable per server instance for each parent entity type (event, case)?

**Comment by MateStrysewske** [comment]
@bernardsilenou No, task types aren't configurable at all at the moment

**Comment by MateStrysewske** [comment]
@bernardsilenou You had added this image to the issue:

https://github-production-user-asset-6210df.s3.amazonaws.com/12996724/239054881-624feccd-4480-41ec-9024-69b017fa77f5.png

Is this really needed? I feel like it should be enough to have the "Environment" task context in the filter; there's currently no way to differentiate between environment and animal tasks anyway, and differentiating between human and environment tasks is also relatively hard because were should e.g. tasks that aren't associated to any entity go?
