### ISSUE TITLE
Explain inconsistent infrastructure data in several files [1]

### ISSUE THREAD

**Issue by fhauptmann** [SORMAS-Foundation/SORMAS-Project#11981]
### Problem Description

There are at least three locations where infrastructure data is imported from: 

 * https://github.com/hzi-braunschweig/SORMAS-central-data/tree/main/import/csv
 * https://github.com/hzi-braunschweig/SORMAS-central-data/tree/main/out
 * https://github.com/hzi-braunschweig/SORMAS-Project/tree/development/sormas-backend/src/main/resources

Some of the sources miss e.g. uuid what leads to unexpected behaviour when activating S2S. Maybe there are more inconsistencies. 

### Reproduction Steps

1. import from  https://github.com/hzi-braunschweig/SORMAS-central-data/tree/main/import/csv
2. activate S2S

### Expected Behavior

S2S will synchronize data from S2S central. 

### Affected Area(s)

Web app, ReST API

### SORMAS Version

SORMAS 1.82.0 

### Android version/Browser

every browser

### User Role(s)

S2S

### Server URL

https://akademie.sormas-deutschland.de

### Additional Information

We must consolidate infrastructure data to be stored on one location only.

**Comment by MartinWahnschaffe** [comment]
I looked into and realized that it actually does make sense to have those three places. 
What is definitely missing is:

- [ ] a readme on what's the purpose of those places and how to properly use the data.
- [ ] The import folder should probably be renamed to "source" or something similar

Besides providing the data (data in output folder), SORMAS-central-data also provides a mechanism to clean-up and add uuids to existing data (in the import folder). 
The import folder currently contains a mix of csv and sql of different sources, so that definitely also needs to be explained (and maybe cleaned up) a bit more.

The data in sormas is supposed to be a copy of the continent, sub continents and countries in the out directory. There is unfortunately no better way to handle this, because I wouldn't want to include this repository in SORMAS-Project. Furthermore this data VERY rarely changes, so it should not be an issue.

- [ ] Of course a readme should be added to the data in SORMAS-Project so everyone understands that the data is a copy
