### ISSUE TITLE
[Event groups] Clicking 'Link event group' leads to an error when the user does not have the 'Create new event group' right

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12008]
### Bug Description

When a user does not have the right 'Create new event groups' and they try to link an event to a group, an error appears.

### Reproduction Steps

1. Configure a user that has all the rights except the 'Create new event groups';
2. On an existing event, click on the 'Link event group' button.
Actual behavior: An error appears.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/cecf722a-dfab-4ba3-a67d-fdb3cd6535c5)

Logs from the local machine:
[logs create new event groups.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/11591769/logs.create.new.event.groups.txt)

### Expected Behavior

The user should be able to successfully link the existing event groups to the event. The missing right should only prevent them from creating new event groups. 

### Affected Area(s)

Web app

### SORMAS Version

1.85.0; 1.84.0; 1.83.0

### Android version/Browser

Chrome

### User Role(s)

Configured user that does not have the 'Create new event groups' right

### Server URL

local machine; https://release-international.sormas.netzlink.com/

**Comment by carina29** [comment]
Updates and changes agreed with @adinaflorea9 :
After fixing the described bug, some other bugs appeared on the flow of linking an already created event group or linking a new event group. These bugs were also solved in this ticket.

**These findings led to some changes related to the required user rights:**
The case when the logged in user has EVENTGROUP_CREATE right but does not have EVENTGROUP_LINK right will not exist anymore (in the past the user was prompted with a UI message when tried to link the newly created eventgroup without  EVENTGROUP_LINK right). 

=> When the EVENTGROUP_CREATE right will be selected from the user rights, the EVENTGROUP_LINK right will also be automatically selected and in this way the above mentioned case will not exist anymore.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/8b632807-477a-4d53-8b10-982673c31373)

Therefore the following combinations will exist:
1)None of the rights ( EVENTGROUP_CREATE,  EVENTGROUP_LINK will be present) -> the button link "Link event group" will not appear
2) EVENTGROUP_CREATE and  EVENTGROUP_LINK ( the second one will be automatically selected) -> the button will appear and the heading of the modal window will be "Pick or create event group"
3)Only EVENTGROUP_LINK right -> heading will be "Pick event group"

**Comment by AndyBakcsy-she** [comment]
This bugfix also introduced a new user right dependency:

When EVENTGROUP_CREATE is selected, will be automatically selected EVENTGROUP_LINK right too.

Related to the bug, from now on we will have the following combinations in relation with the existent user rights when we want to link an event to an event group:

Only EVENTGROUP_LINK right -> heading will be "Pick event group" ( an event group can be selected from the already existing event groups)

EVENTGROUP_CREATE and EVENTGROUP_LINK rights -> the heading of the modal window will be "Pick or create event group"

If none of the EVENTGROUP_CREATE , EVENTGROUP_LINK rights are present the “Link Event Group“ button will not appear.

The default user roles were not affected by this change because all the default user roles which had EVENTGROUP_CREATE right also had EVENTGROUP_LINK right:

Admin, NATIONAL_USER, SURVEILLANCE_SUPERVISOR , ADMIN_SUPERVISOR, SURVEILLANCE_OFFICER, COMMUNITY_OFFICER, CONTACT_SUPERVISOR, EVENT_OFFICER.

An SQL migration script was added in order to add the EVENTGROUP_LINK right to all the users which had EVENTGROUP_CREATE right without having EVENTGROUP_LINK right.
