### ISSUE TITLE
Add a create/edit form for environments in the mobile app [5]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12030]
### Feature Description

After an Environment entity has been created in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11796 as part of epic https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11533, create and edit forms for this entity are now required for the mobile app.

### Added Value/Benefit

Users will be able to create and edit environment entities for further usage in the system.

### Acceptance Criteria

- [ ] A creation form for environments has been added with the following fields:
  - Report date (required)
  - External ID
  - Environment name (required)
  - Environment media (required)
  - Location form (region, district, gps lat and gps lon required; region and district read-only and pre-filled with the jurisdiction of the user)
  - Responsible user (contains a list of all users with the `ENVIRONMENT_EDIT` user right that are assigned to the district selected in the location form)
- [ ] An edit form for environments has been added with all fields from the creation form and the following additional fields:
  - UUID (read only)
  - Reporting user (read only)
  - Investigation status (required)
  - Water type (if environment media == water)
  - Other water type (if water type == other)
  - Infrastructure details (if environment media == water)
  - Other infrastructure details (if infrastructure details == other)
  - A "Water use" heading (if environment media == water)
  - Checkboxes for all `WaterUse` enum values (if environment media == water); see epidemiologicalEvidenceDetails of events in the web app for reference - this hasn't been implemented in the mobile app so far
  - Other water use (if the checkbox for "Other" water use has been checked)
- [ ] A button to create a new environment has been added to the environment list created in #12025 that brings up the creation form
- [ ] Clicking on an environment in the environment list created in #12025 takes the user to a dedicated page for the environment, displaying the edit form
- [ ] The location form includes the functionality to pick the current GPS coordinates of the user

**Comment by adinaflorea9** [comment]
I am reopening the ticket as when trying to save the edits made on all of the fields of an existing environment the following error appears in the mobile app:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/67bdc6d8-4cd5-475b-ac5a-0c9cae6b43bf)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:
1. Location - is not prefilled with the region and district assigned to the user that is currently logged in the android app;
2. In creation and edit forms the fields for region and district are marked as mandatory but the forms can be successfully saved without having any information there - should be fixed by point 1; but keep in mind that this should apply only in the mobile app and in the web app it should 
3. Synchronization count - when creating or editing environment entities (either in the web or mobile app) the synchronization counts them in pathogen tests and/or additional tests. They should be counted in environments.
4. 'Other infrastructure details' field does not appear in the mobile app (edit form) when 'Other' is selected in the 'Infrastructure details' filed.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the following field is not displayed in the mobile app if 'Water Type' = other:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/d42a70c5-9a76-4b8d-bc38-6e4c0d1bb784)

Should be as in the web app:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/a718b437-9d0a-41cf-8812-d2f534881de6)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine suing the latest version of SORMAS from the development branch - 1.88.0-SNAPSHOT(86fec9b).
