### ISSUE TITLE
[DEMIS] Book icon lab - De-link, new lab message ID, backlink

### ISSUE THREAD

**Issue by AliciaRaber** [SORMAS-Foundation/SORMAS-Project#12229]
### Problem Description

After executing the script from ticket #11763 we found out that the lab sample-id is not unique. Therefore the connection between a lab message with the same number can be accessed in the same case. It is also possible to search for the lab message-ID in the sample directory. This results in displaying multiple persons in the case (accessible via move page forward).
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91321821/19d0b30b-5163-482d-b661-fd6979fd7721)

### Proposed Solution

1. First it is necessary to unlink all connections with lab message-ID who are not in the uuid-format. The format of the affected lab messages is different.
2. After unlink we have to modify the lab message-ID to a unique format.
3. Third step is to run the script from original ticket again in order to create a 1:1 connection between a lab message tho the exact case.

### Additional Information

Further information about the progress of the ticket can be found under issue #11967

**Comment by AliciaRaber** [comment]
@adinaflorea9 Please let me know if you need further information about the issue.

**Comment by adinaflorea9** [comment]
@AliciaRaber Thank you! I will - I marked it with the labels and saved it so that the team can discuss it in the meetings next week. I will reach out if any more information is needed :)

**Comment by abrudanancuta** [comment]
For the 1st point a script needs to be created in order to make the unlink of the samples that were affected from the last script. Here to have the unlink script running for the same time period the link script ran

For the 2nd point a new ticket was created https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12301

For the 3rd point to re-establish the connection between sample and lab message, a new script needs to be created based on first name, last name, birthday and message date

**Comment by leventegal-she** [comment]
@AliciaRaber @abrudanancuta 

1. In order to unlink the messages we need the result of linking them so we know which ones were affected, in the worst case we can delete all links in the period the restore script was ran but this may delete more links than wanted.
2. If the specimen ID is not used as expected then we just don't use it in SORMAS. This means we won't have any unique id that we know for sure which demis message links to which which external message and sample in SORMAS. Maybe there is an other field on the demis message that could be used as unique identifier and we can map it into the external message. Note that this point is not needed to solving the current issue, it could be helpful for handling similar problems in the future.
3. To re-establish the connections we can use "first name, last name, birthday and message date" as @abrudanancuta suggested. But first let's have a check if the affected messages have all these fields.

Before creating the new script please run the following script for the period we want to restore the links:
```sql
select count(em.id) as total_count, (select count(em2.id) from externalmessage em2
                                  where (em2.personfirstname = '') IS NOT TRUE
                                    and (em2.personlastname = '') IS NOT TRUE
                                    and (em2.personlastname = '') IS NOT TRUE
                                    and em2.personbirthdateyyyy is not null
                                    and em2.personbirthdatemm is not null
                                    and em2.personbirthdatedd is not null
                                    and em2.messagedatetime BETWEEN ? AND ?) as restorable_count
from externalmessage em
where em.messagedatetime BETWEEN ? AND ?;
```

Please use the same period for both `messagedatetime` condition and tell us the numbers this query produces so we can decide to do the script or find other solution(s)

**Comment by AliciaRaber** [comment]
@leventegal-she Our technicians have run the script. Results are attached as picture.
Please let me know if you need further information.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91321821/a165aefe-f641-4a85-89af-8c76de097c82)

**Comment by AliciaRaber** [comment]
Result of this Excel show the result of the connections made. Script has been applied at 15.06.2023
[restored__2021-01-01_00_00_00.000__2023-01-01_23_59_59.999.csv](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12258392/restored__2021-01-01_00_00_00.000__2023-01-01_23_59_59.999.csv)

Result of this Excel shows the possible links which could have been re-established
[possible_links__2021-01-01_00_00_00.000__2023-01-01_23_59_59.999.csv](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12258399/possible_links__2021-01-01_00_00_00.000__2023-01-01_23_59_59.999.csv)

**Comment by leventegal-she** [comment]
The script for cleaning up the links created earlier:

```shell
psql -d sormas_db3 -v output=/tmp/cleared_links.csv -v restore_result=/tmp/restored__2021-01-01_00_00_00.000__2023-01-01_23_59_59.999.csv < clear_links_restored_reviously.sql  2>&1 | tee /tmp/result_clear_links
```

**NOTE** the file path for `restore_result` should be the path to the `csv` file resulted by running the previous version of restoring links script. 

For searching for possible links please run:

```shell
psql -d sormas_db3 -v message_from='2023-04-14 00:00:00.000' -v message_to='2023-04-14 23:59:59.999' -v output=/tmp/possible_links_by_person__ 2023-04-14 00:00:00.000__ 2023-04-14 23:59:59.999.csv < check_links_by_person_and_report_date.sql   2>&1 | tee /tmp/result_check_links_by_person__ 2023-04-14 00:00:00.000__ 2023-04-14 23:59:59.999
```

The following script crates links between external messages and samples based on person data, message date and lab sample id.

> NOTE: Even if *lab sample id* is not a unique identifier it should be used in these queries to decrease the possibility to link a external messages to samples not coming from DEMIS.
 
```shell
psql -d sormas_db3 -v message_from='2023-04-14 00:00:00.000' -v message_to='2023-04-14 23:59:59.999' -v output=/tmp/retored_links_by_person__ 2023-04-14 00:00:00.000__ 2023-04-14 23:59:59.999.csv < restore_links_by_person_and_report_date.sql   2>&1 | tee /tmp/result_restore_links_by_person__ 2023-04-14 00:00:00.000__ 2023-04-14 23:59:59.999
```

Change the date and time values as needed, just keep in mind to use the same value for  `message_from` and the first date time of the *output* and *result* file names and same for `message_to` and the second date time in the output and result file names.

**Comment by abrudanancuta** [comment]
Some samples remained unconnected because some person's name were written with capital letters in Sormas or Demis lab. 
As a feedback from the run made on Nuremberg department, the first name and last name doesn't need to be a difference if they have capital letters or small letters.  
The script need to be adjusted to ignore capital or lower letters.

**Comment by leventegal-she** [comment]
@abrudanancuta @AliciaRaber 
The scripts search for person names case insesitively and also removes empty characters around the names

```
        AND (LOWER(CONCAT(TRIM(em.personfirstname), ' ', TRIM(em.personlastname))) = LOWER(CONCAT(TRIM(cap.firstname), ' ', TRIM(cap.lastname)))
             OR LOWER(CONCAT(TRIM(em.personfirstname), ' ', TRIM(em.personlastname))) = LOWER(CONCAT(TRIM(cop.firstname), ' ', TRIM(cop.lastname)))
             OR LOWER(CONCAT(TRIM(em.personfirstname), ' ', TRIM(em.personlastname))) = LOWER(CONCAT(TRIM(epp.firstname), ' ', TRIM(epp.lastname))))

```
^ `LOWER` transforms all to lower case and `TRIM` removes empty characters like spaces

Something else must be the issue, maybe the birth date or the lab sample id is different

**Comment by AliciaRaber** [comment]
New run for script:
Part 2: psql -d sormas -v message_from='2023-01-01 00:00:00.000' -v message_to='2023-03-31 23:59:59.999' -v output=/tmp/possible_links_by_person__2023-01-01_00:00:00.000__2023-03-31_23:59:59.999.csv < check_links_by_p
erson_and_report_date.sql   2>&1 | tee /tmp/result_check_links_by_person__2023-01-01_00:00:00.000__2023-03-31_23:59:59.999

**Comment by AliciaRaber** [comment]
@abrudanancuta @markusmann-vg @MateStrysewske 
I would like to clone this issue. I have commented the actual script with the right database reference.
Please let me know if you need further information.

**Comment by abrudanancuta** [comment]
The original ticket from HelpDesk was closed having the Resolved status as resolution.
