### ISSUE TITLE
Rename lab sample id to Specimen id

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12301]
### Problem Description

At the moment when processing a lab message, the mapping of Specimen id that comes from Demis  is done in Sample with the field lab sample id.

We found out that health departments are not using the Specimen id as a unique id generated each time a lab message is generated.

### Proposed Change

It is proposed to rename the lab sample id field with Specimen ID because in this way will be easier to know that this field is something specific from Demis.
Also an info icon next to the field could be added for explaining the field from where is coming and also specifying that there is a high probability that is not unique in the Demis system

### Added Value/Benefit

Have a clear line between the IDs from Sormas and IDs from Demis external messages

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

**Comment by MateStrysewske** [comment]
@abrudanancuta I'd heavily vote against implementing this because it would be a breaking API change for ALL users of SORMAS. The field `labSampleId` is used in other countries as well and doesn't relate to DEMIS there in any capacity.

If such a renaming is desired, it should be done via Crowdin in the German translation.

**Comment by abrudanancuta** [comment]
As the field is already used for other countries and is not Demis specific, then this ticket will be closed.
