### ISSUE TITLE
Allow users to send mails to case, contact, event participant and travel entry persons [5]

### ISSUE THREAD

**Issue by SORMAS-ChristopherMeyer** [SORMAS-Foundation/SORMAS-Project#12463]
### Feature Description

Add a new "Emails" side component to cases, contacts, event participants and travel entries, and allow users to send emails based on email templates to the associated person.

### Added Value/Benefit

Users will be able to send external emails through SORMAS without having to go through an external email client and having to manually fill in information all the time.

### Acceptance Criteria

- [x] A new "Emails" side component has been added to cases, contacts, event participants and travel entries
- [x] A "Send email" button has been added to the component
- [x] When the associated person has no email address specified, a hint is displayed in the component: "Case/contact/event participant/travel entry person has no email address specified" and the button is disabled
- [x] Clicking on the button brings up a popup that allows the user to configure and send the email:
  - [x] A "Choose template" dropdown contains all email templates for the respective entity and allows the user to choose one
  - [x] An "Email address" dropdown contains the primary email address and, if available, all additional email addresses from the person contact details entities associated with the person
  - [x] The primary email address is selected by default and has a `(primary)` suffix; this suffix is translatable through i18n
  - [x] The user can close the popup with a "Discard" button, or send the email with a "Send" button; when the send button is clicked and the template or email address dropdowns are empty, show an error notification and tell the user to select an email template and an email address
- [x] The new components are only visible for users with the `EXTERNAL_EMAIL_SEND` user right introduced in #12466 and when the new `EXTERNAL_EMAILS` feature type introduced in #12461 is enabled
- [x] It's verified that emails sent this way are actually sent

### Mockups

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96547924/87c17ee3-c8f7-46cd-8f7f-21f8ceeb2cd0)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/65529128/3a1f5836-1d6e-4e4e-945f-23d62089aa82)

### Additional Information

Password protection and document attachment will be handled in separate issues.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:
- [ ] event participant page - email missing hint has a spelling error (two words are stuck together);

- [ ] when only non-primary email address exists - the default selection in the email dropdown just shows (primary) - should either show nothing or one of the other email addresses (just showing primary could confuse the user to think that it means they are using the primary email address when in fact it is missing);

- [ ] the warning message in the above situation should also be updated to say the name of the field as it is displayed in the UI and not the one from the code (appears when clicking send but in the email dropdown only the word primary is displayed);

- [ ] for users restricted by jurisdiction - if the entity is not owned, outside jurisdiction the button and card is enabled but sending can not be done as the information is confidential - card should be disabled if responsible or disease jurisdiction do not match the user and they do not have ownership over the entity.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(a10d1df).
