### ISSUE TITLE
Add an environment sample list to the mobile app [3]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12468]
### Feature Description

This issue is part of the EPIC https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11533 on the environmental surveillance module. Add a new environment sample list to mobile app. Use a new menu entry for this instead of integrating the list into the existing sample list (i.e. different to the web app).

### Added Value/Benefit

Users will be able to work with environment samples in the mobile app.

### Acceptance Criteria

- [x] A new menu entry point "Environment samples" has been added
- [x] The new menu entry is only visible to users with the ENVIRONMENT_SAMPLE_VIEW right
- [x] The menu entry contains a list of environment samples with the following values; add styling that matches the other directories to the individual elements and make it as similar to the existing sample list as possible and sensible:
  - Sample material
  - Collection date
  - Short UUID
  - Associated environment
  - Laboratory
- [x] The list can be filtered by shipment status (like the existing sample list)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following - synchronization of the mobile app does not work if an environmental sample exists but the logged in user does not have rights over environmental samples.

Steps:
1. Created an environmental sample within the user's jurisdiction directly from the DB;
2. Synchronized it to the mobile app (use a default environmental surveillance user);
3. Logged out of the mobile app;
4. Stopped the mobile app, re-started it and re-synchronized it so that the user's rights are also updated;
5. From the web app, removed the user's rights over environmental samples;
6. Restarted the mobile app and logged in with the user.
Actual behavior: The regular synchronization does not work as it shows the following:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/78b27a5b-0403-4177-8268-2636d09cf06c)

Logs from the server:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/93b381a7-85c1-4fb5-8fbb-6324db0e1533)

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the issue mentioned in the comment above is still reproducible with a regular synchronization of the mobile app - SORMAS version 1.89.0-SNAPSHOT(dab979d).
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/fb6ff11b-9fbe-485a-b03d-e42a3ed4acef)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/f289d7d6-669f-4e42-b35d-d434225a081d)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.89.0-SNAPSHOT(a40591b).
