### ISSUE TITLE
Add a line-listing feature to event participants [5]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#12604]
### Feature Description

-  Users are required to return to the event participant directory each time a new ep is recorded, thus leading to much time wasted.
-  As a user, I would like to list all the ep as fast as possible in one view (like the line listing feature in the web app) or sormas should present me with the option to "save and create another" after filling in the creation form for an ap.
- Add the line listing to ep directory in the web app
- Add the option  "save and create another" to the mobile app just like already implemented for cases (when line listing is enabled for the respective disease from the Configuration -> Line Listing view of the web app)

### Added Value/Benefit

- users would be able to create event participants faster and then complement the non-requited information at a later.

### Acceptance Criteria
Web app:
- [x] A "Line Listing" button has been added to the event participants view
- [x] When clicking on the new button, a popup is opened that allows the user to create as many event participants for the event as they wish, similar to the case line listing window
  - Responsible region and district are displayed under a heading "Shared information"; whether or not they're required depends on whether there's a region and district specified for the event (same logic as when creating individual event participants)
  - First name, last name, sex (all required) and involvement description are displayed in one line below a "List of new event participants" heading
  - An "Add line" button allows users to add new event participants to the list
  - Delete buttons (displayed as a trash can icon) are added to all lines and delete the respective line; when only one line is present, the button is disabled
  - Saving saves all the individual event participants ONLY if there are no validation errors (i.e. only when all required fields have been filled in)
  - Person AND event participant duplicate detection is done live for each event participant; i.e. when two identical event participants are saved, the second one should be detected as a duplicate event participant (similar to how we already do it for cases and contacts in line listing)

Mobile app:
- [x] Add a checkbox to the top of the event participant creation fragment: "Use rapid event participant entry"
- [x] If the checkbox is checked, after saving, don't redirect the user to the event participant edit fragment, but instead allow them to create another event participant; take over the responsible region and district from the previously entered event participant

### Implementation Details

See rapid case entry in the mobile app and implement the rapid event participant entry similarly

**Comment by adinaflorea9** [comment]
I am reopening ticket due to the following:
- [ ] event owned outside disease jurisdiction - can not add event participants regularly but can add them via line listing - should not be possible to add via line listing;
- [ ] event not owned outside disease jurisdiction - can not add event participants regularly but can add them via line listing - should not be possible to add via line listing;																																 - [ ] event not owned outside responsible jurisdiction - an not add event participants regularly but can add them via line listing - should not be possible to add via line listing.

**Comment by bernardsilenou** [comment]
@adinaflorea9 @MateStrysewske 
When an ep is added using the rapid entry in the mobile app, the moment I save it, there is an orange pop-up message, it disappears so fast that I cannot read its content. 
Since we often use orange messages for warnings, it keeps me wondering if it's a bug or a feedback message to the user..

If ist part of the development, then maybe we can use a green background and increase the duration.

I tested on release-international , Version: 1.92.0 using the Surveillance officer role

**Comment by adinaflorea9** [comment]
@bernardsilenou I will check it out and will let you know 😄

**Comment by adinaflorea9** [comment]
@bernardsilenou @MateStrysewske I checked the behavior and this is what the orange message states:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/1bc2473d-268c-4c07-a8cc-2105adbd57fe)

The message appears right after the user clicks to save the new event participant and immediately after the message disappears the event participant form is empty so that a new one can be created with the rapid entry feature. 

@MateStrysewske I am not sure if the message could be updated, as the part that the event participant form was refreshed is correct, as after the message appears the form is empty, but the part about the unsaved changes discarded could perhaps be updated? As the message only appears when the user has already saved the previously entered data. 

The time that the message is on screen is very short, is there a possibility to lengthen it? I could only capture the screenshot by using a screen recorder and then pausing the video recorded.

**Comment by MateStrysewske** [comment]
@adinaflorea9 I think we should try to get rid of that message in this situation because it doesn't really make sense. Afaik its purpose is to be shown when editing an existing event participant and making changes while the same event participant has been updated in the meantime (e.g. during synchronization). This doesn't apply to newly created event participants under any circumstances.
