### ISSUE TITLE
If GPS latitude and longitude are added without a Region or District the Android app crashes

### ISSUE THREAD

**Issue by carina29** [SORMAS-Foundation/SORMAS-Project#12780]
### Bug Description

If GPS latitude and longitude are added without a Region or District the Android app crashes with different errors based on the entity.

### Reproduction Steps

Cases:
1. Open a Case and click de Pencil icon for editing
2. Go to Person Information -> Home address and add/edit a longitude and latitude and do not complete the Region and District
3.  Save the change and check the Case line listing
=> A new duplicate case will be created which will disappear after a synchronization

**Expected behaviour:** The duplicate case should not appear
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/13bbb243-1f0e-4410-85de-ee0a710b7631)

Contacts:
1. Open a Contact click de Pencil icon for editing
2. Go to Person Information
3. Add or edit a GPS latitude and GPS longitude and click "OK". 
4. Click Save and go to the Contacts listing
5. The app will crash with an exception
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/c519cccf-460f-4677-9316-d83b2530a3df)

Events:
1. Open an Event click de Pencil icon for editing
2. Go to Person Information
3. Add a country for which we do not have a district and region ( example Albania)
4. Add a GPS latitude and GPS longitude and click "OK". 
5. Click Save and go to the Events listing
6. The app will crash with an exception
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/b15ef5fc-26bd-4884-9613-69d6291d4ee0)

Please check the above steps for other entities too as it is described in the "Expected Behaviour" Section of this ticket

### Expected Behavior

Check for all the places mentioned in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/9201 ticket the combination of having a completed GPS latitude, GPS longitude without a District, Region. 

The expected result is to not throw any exception in the described scenarios after saving, checking the line listing of the entity or during synchronization with the web app and do not create duplicate entities after saving.

### Affected Area(s)

Android app

### SORMAS Version

SORMAS 1.91.0

### Android version/Browser

Android

### User Role(s)

Surv Off

**Comment by leventegal-she** [comment]
First issue introduced by [#4837](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/4837) thus reopening it

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:
When editing an existing event in the mobile app, and setting a country with no region and district for its location, in the list of event and on the event view page the name of the country is displayed for the location. However, when doing the same in the web app and then synchronizing those changes to the mobile app, the event location now says 'Location N/A'. The expected behavior is that both for the event modified in the mobile app and the event modified in the web app and then changes synced to the mobile app, the location of the event would display the name of the country selected, when no region and district are available.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/4aad3e9e-3919-4f01-9323-dfc9c261b678)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.92.0-SNAPSHOT(a10d1df).
