### ISSUE TITLE
Add support for the hide jurisdiction fields feature to campaigns [1]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#12809]
### Feature Description

The option to hide jurisdiction fields introduced in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12550 needs to be applied to the campaign module as well.

### Added Value/Benefit

Countries that don't use jurisdictions will be able to use the campaign module.

### Acceptance Criteria

- [ ] If the `HIDE_JURISDICTION` feature is enabled, hide all jurisdiction fields and automatically fill the region, district, and community fields with the respective default options by using the getDefaultInfrastructure method (see CaseCreateForm and CaseDataForm)
- [ ] If the feature is enabled, the jurisdiction filters and columns in the campaign directories are hidden

**Comment by carina29** [comment]
@MateStrysewske When the HIDE_JURISDICTION feature is enabled, the Region, District and Community dropdowns will be hidden and the default values will be considered.
I think that the Area dropdown should also be hidden in this scenario, right? 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/1766d1eb-3beb-4ef0-b434-c4976c79bce8)

**Comment by carina29** [comment]
When there will be no defaults set for Region , District and Community as an outcome we will have also null value set from the code for Area. In this case the below validation message will appear (even if the Area will not be displayed because of the enabled HIDE_JURISDICTION). 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/9d698b77-be17-4535-8529-34d59d8e98f8)


When default values are set (for Region, District and Community) the default value for Area will be considered the default Region's Area.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.94.0-SNAPSHOT(e455ff9).
