### ISSUE TITLE
Problem redirection to home page after connection

### ISSUE THREAD

**Issue by meriem3333333** [SORMAS-Foundation/SORMAS-Project#12847]
### Bug Description

![Capture d’écran sormas](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/154965806/b948232c-3dd2-496f-a050-c801c77ae880)
![Capture d’écran sormas2](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/154965806/e828c41b-80c0-4893-90c8-53611acfb524)
![Capture d’écran sormas3](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/154965806/824f1007-b0da-4cfa-ac50-494e14b032c9)

### Reproduction Steps

1.
![Capture d’écran sormas](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/154965806/99d2f021-4b67-497d-abfb-6eb4375c282a)
![Capture d’écran sormas2](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/154965806/18fd5fc8-ee86-411e-a15a-2dfb9bfa2444)
![Capture d’écran sormas3](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/154965806/4f880160-3f95-405d-a1fb-414436813153)

2.
...

### Expected Behavior

The application has been working fine for 2 weeks, but this time when I log in, I encounter a redirection issue. 
After authenticating, the 'login' button remains grayed out and doesn't proceed to the interface.'"

### Affected Area(s)

Web app

### SORMAS Version

1.67.0

### Android version/Browser

google chrome

### User Role(s)

admin

**Comment by adinaflorea9** [comment]
@whomvever picks up the issue - please note that the version mentioned in the ticket is 1.67.0 - we currently are on the development environment at version1.94.0

@meriem3333333 could you also please attach a screenshot with the tab in 'Inspect' set to 'Network' at the time that you try to log in? Just so that we can see what error is displayed there exactly.
