### ISSUE TITLE
Search by NationalID is not consistently working in all locations

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13029]
### Problem Description

When you are searching for the NationalID in the cases directory, the search does not include the NationalHealthID field. 

### Proposed Change

The search by NationalID should be included in the search input field for ID, externalID, facility in every form. 
For case and contact grids the search for NationalID will be performed if a text will be inserted to either "Person related search filter text box" or "Case/Contact related search filter text box"

### Added Value/Benefit

Users can search by the NationalID and increase the speed of processing cases, contacts etc.

### Acceptance Criteria

- [ ] Searching for NationalID delivers results in the case, contacts and other forms
- [ ]
- [ ]

**Comment by carina29** [comment]
I'm reopening this ticket because currently the National ID filter is added to the Person ID/name/contact... filter instead of ID,EPID,Number,external ID filer as it is requested in the ticket description.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/ee108423-ee1f-443c-8e43-32c5f35de404)

**Comment by richardbartha** [comment]
Tested on web local setup version 1.96.0-SNAPSHOT ([https://github.com/sormas-foundation/SORMAS-Project/commits/93d6439e42f5955f31cb43246979b340ff50cf26])
