### ISSUE TITLE
Create a new Self Report entity and IndexDTO

### ISSUE THREAD

**Issue by markusmann-vg** [SORMAS-Foundation/SORMAS-Project#13059]
### Feature Description

With the new module for self report, we need a new entity which is independent from the others to be used in the frontend. 
The new entity will only be used in the web-app and not in the mobile app.

### Added Value/Benefit

To be able to process self reports in SORMAS this is the first step. 

### Acceptance Criteria

- [x] A new SelfReport entity (extending CoreAdo) has been added with the following fields
- Date reportDate (Report date)
- User reportingUser (Reporting user)
- User responsibleUser (Responsible user)
- Processing Status
- Type 
- more? => We requested a sample file. 

- [x] A corresponding DTO and ReferenceDto have been created, along with a facade (extending CoreFacade) and service
- [x] A SelfReportndexDto has been added with the following fields:
- UUID
- processingStatus
- [x] A new SelfReportInvestigationStatus enum has been added with the following values:
-     In progress
-     Pending
-     Completed
-     Rejected 
- [ ] i18n has been added for all new fields/enum values

**Comment by bernardsilenou** [comment]
@markusmann-vg 
- Since the self-declared (would suggest the name self-notified or self-reported) entities can be any of the entities in sormas, can this issue be addressed by adding a new user role/right that permits non-health workers to report entities? 
- We can then add filters to each directory to show or exclude them + option to process (approve) them
-ie to add "self-notified" entities will be those with reporting user == not health health worker, a person can also report a case for their friend or child thus not self.

**Comment by markusmann-vg** [comment]
- I like self-reported and yes, we should add a new user role/right for this, even if it's a system user and it's reporting via API in first place. Once we implement the citizen portal to self-report, every user that self-reports will have this user role then.

- good idea, pls. tell us more about it in the planning so that we can create a ticket for this

**Comment by leventegal-she** [comment]
Changed "self declaration" to "self report"

**Comment by carina29** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.96.0-SNAPSHOT ([1d1eb96](https://github.com/sormas-foundation/SORMAS-Project/commits/1d1eb9b022c351162989e1c35f6dfe75bb2bf151))
