### ISSUE TITLE
Add a user interface for customizable enum values [13]

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#6340]
### Situation Description

Thus far, the customizable enum value table only exists in the database and there is no user access via the UI. Since this table allows customization of a users Sormas instance, admins should be able to manage entries via an interface in the configurations menu

### Feature Description

Add a new tab to the configuration view that allows users with the respective rights to edit and remove existing and add new enum values to customizable enums.

### Added Value/Benefit
Users don't have to rely on technical admins to manipulate the database. Also, going through the interface instead of directly doing changes in the database means that the data can actually be validated.

### Acceptance Criteria
- [x] Add a new `CUSTOMIZABLE_ENUM_MANAGE` user right granted to user roles deriving from the default admin role
- [x] Add a new tab called 'Customizable Enum Values' to the configurations screen; make sure to update the logic that grants users access to the configurations with the new user right
- [x] Add a table which includes the following columns
    - edit icon (no caption)
    - `datatype`
    - `value`
    - `caption`
    - `diseases`
    - `properties`
- [x] Add general filters above the list
    - free text search field for: value, caption
    - datatype - drop-down only for data types included in the list
    - diseases - drop-down only for diseases included in the list
- [x] Add a creation button at the top right
    - When clicked, open a customizable enum value entry form
        - datatype (drop-down including the available data types) - compulsory
        - value (free text) - compulsory, validate for uniqueness in datatype and proper format
        - caption (free text) - compulsory
- [x] When clicking the edit icon, open an edit window which is similar to the creation form plus additional fields:
    - translations (should include a multi selection option with the available languages - `languageCode` - plus a subsequent free text `value` translation field
      - the same `languageCode` should not be able to be selected more than once
    - properties
    - diseases (multi selection option to specify any available diseases)
    - Also show the uuid of the entry (non-editable) at the top
    - Add buttons to discard and save
    - Disable datatype and value fields
- [x] Add an info button to the left of the creation button
    - Upon clicking, open a pop-up with explanations on how to use the customizable enum value configuration section

### Additional Information

![Configurations customizable enum values](https://user-images.githubusercontent.com/70317594/176898353-0c3be0b0-ccd8-4f42-a83e-3d555ddd1ebe.png)
![New value](https://user-images.githubusercontent.com/70317594/176898368-f090c3df-a117-4657-a4cc-c148b0345c06.png)
![Edit value](https://user-images.githubusercontent.com/70317594/176898379-49fd6a1c-e1b6-49fa-b685-9ac87d299ca9.png)

**Comment by kwa20** [comment]
@MateStrysewske Please adjust anything if necessary :) 

Customizations in https://github.com/hzi-braunschweig/SORMAS-Project/issues/5225 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/3880 could be solved with this feature. We might have to allow further specifications for handling customization per respective entity though.

**Comment by kwa20** [comment]
@MateStrysewske I added some mock-ups for some design suggestions. Whenever you have time I'd appreciate your feedback :)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:
1. The 'Search' filter from the grid - the hint displayed in it is 'Search'. Instead, display the hint 'Value, caption' since these are the only values that the user can use that filed to search/filter based on;
2. For the enums that remain associated with a disease that has been deactivated: 
Steps:
- enable a disease from the DB - Diphteria
- add it to one of the customizable enums 
- deactivate the disease 
Actual hebavior:
-> if Diphteria was the only disease added to that enum, it remains displayed in the main grid but not on the edit form; the enum can no longer be set to have the default value of 'All diseases' because Diphteria can not be unchecked anymore;
-> if Diphteria was not the only disease added to that enum - it remains listed in the main grid among the diseases associated with that enum, or counted if the diseases are above 11 and we display the counter;

Similar to the request from ticket #11435 treat the checkboxes associated with diseases that have been deactivated:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/9599dd54-c59b-4293-9756-d06628aeffe7)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.93.0-SNAPSHOT(2eb4afc).
