### ISSUE TITLE
change of user language leads to wrong language being displayed for navigation and first symptom

### ISSUE THREAD

**Issue by zart-sudo** [SORMAS-Foundation/SORMAS-Project#6920]
### Bug Description
If the user changes his language via user settings while looking at cases / symptoms the field "first symptom" always displays in the language it has been saved in. 

Furthermore, if the user uses SORMAS in multiple browser tabs and changes the language on one, the language of the navigation bar only refreshes on the active tab so it's inconsistent between the navigation and the displayed details on the right for the other tab(s).

### Steps to Reproduce

**First symptom**
1. Select any symptom as first symptom and save.
2. Change user language.

**Navigation Bar**
1. Open atleast two tabs of SORMAS with the same user.
2. Change user language in one.
3. Check the other tab(s).

### Screenshots

**First Symptom**
![first symptom](https://user-images.githubusercontent.com/80318778/136777870-3079fa7d-c8d1-495b-b46c-db8c1482a94f.PNG)

**Navigation Bar**
![navigation bar](https://user-images.githubusercontent.com/80318778/136777357-e4eba8ca-4b14-4dbe-9733-a76f4b3fc950.jpg)

### System Details

* Device: Win10
* SORMAS version: 1.63.1
* Android version/Browser: Chrome
* User Role: Admin / National user

**Comment by FredrikSchaeferVitagroup** [comment]
Thank you for your input @zart-sudo!

Regarding the first symptom: This field actually is a text field. So when cough is chosen as first symptom, the word cough is directly written as such into the SORMAS database as first symptom. If I remember correctly, it has to stay like that for compatibility reasons. 
This text field is not automatically overwritten in the SORMAS database when one user changes their language. That would not be feasible.

Regarding the tabs: for the language to change in the other tabs, they need to reload. A user can reload them manually in the browser to adapt them to the new language setting. How exactly this is done varies from browser to browser, in chrome there usually is this button near the top right corner: 
![image](https://user-images.githubusercontent.com/67001822/137454136-7649b0a1-6477-446f-b81b-65adc8fa004a.png)
For automatically reloading all SORMAS tabs when the user language is changed, SORMAS would probably need a very unappropriate level of control over the user's browser. I don't know whether that is even technically possible, but I doubt that this is desired.

From our developer's perspective, bugs are something that oppose specified behaviour. The points reported in this issue don't do that, so I think we will not change them as a bugfix. If you think those are important points, they would need to be clearly specified and then implemented as a new feature. For this, please open a feature request instead of opening a bug report.

I will leave this ticket open for now, so that another developer can look over this, too.
