### ISSUE TITLE
Remove support for legacy audit mechanism [3]

### ISSUE THREAD

**Issue by JonasCir** [SORMAS-Foundation/SORMAS-Project#8027]
### Problem Description
The overall progress of the new auditing stack is tracked in #7402 combined.
As the implementation of the new auditing mechanism goes on and with the extension of the history tables in place, the existing JPA based audit logging is redundant.

### Proposed Change
With the new audit mechanism being in place for over a year now, we can simply remove the legacy audit mechanism - there is no need to slowly fade it out / deprecate it.

#### SORMAS-Project

- [x] Remove all classes in de.symeda.auditlog.api from the sormas-backend module. The annotations can simply be removed from all classes they are used on.
- [x] Remove the persistence unit from the persistence config
- [x] Remove the audit log connection pool from the domain.xml
- [x] Remove the creation of the audit DB from server-setup.sh, server-update.sh and server-update.conf
- [x] Same for the env variable in the sormas-cargoserver docker config
- [x] Prepare a section for the release notes that explains that the audit DB is no longer used. Also provide commands to backup and delete the audit database.

Note: The audit-logback.xml is part of the new audit mechanism and should not be removed.

### Acceptance Criteria
1. Setting up a new SORMAS no longer creates the sormas audit database
2. For existing systems the sormas audit database is kept, but no longer written to
3. It's safely possible to remove the audit database

### Additional Information
* During import of data from external systems the legacy audit log takes up 14% of the total time, so a small performance improvement is expected, but does not need to be measured.

### Follow-up

- https://github.com/hzi-braunschweig/S2S-Testbed/issues/35
- https://github.com/hzi-braunschweig/SORMAS-Docker/issues/507

**Comment by MartinWahnschaffe** [comment]
Suggestion:

- [ ] Add configuration
- [ ] Disable by default
- [ ] Move setup instructions from the server setup to the documentation of the configuration
- [ ] Mark as obsolete
- [ ] Explain how to remove it in the release notes

**Comment by JonasCir** [comment]
@MartinWahnschaffe Thanks for the list, I agree!

One general question though: What are the pros and cons of completely remove it and just stick with the new approach without the legacy logging behind config? Or should we stick to a deprecation period and remove it in 6 months or so?

**Comment by MartinWahnschaffe** [comment]
I think we need a deprecation period. I'm not a fan of removing big features without giving people some time to adjust.

**Comment by MartinWahnschaffe** [comment]
Additional information on the performance impact of the legacy audit mechanism:
During import of data from external systems the legacy audit log takes up 14% of the total time
![grafik](https://user-images.githubusercontent.com/23217632/196907742-24ebcd57-d855-45eb-8110-1a426999c063.png)

**Comment by MartinWahnschaffe** [comment]
I will rewrite this issue to not deprecate the legacy audit, but directly remove it instead.

**Comment by MartinWahnschaffe** [comment]
Let's merge this issue AFTER the current release, as it's not urgent and a big change that I'd like to test drive a bit during the next development iteration. Furthermore this will allow us to implement the follow-up issues in the same iteration. I'll move this into the TEC teams backlog.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-NSAPSHOT(8988ace).

Verified that in the 'sormas_audit_db' - 'auditlogentry' - no new entries were logged since the merge of ticket 8027. The ticket was merged on the 20th of June and I got the changes on that same day onto my local machine. The last logged entry in that table was on the 19th of June:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/64475613-80e7-45a3-8cc5-6027651ca825)

Verified that I could safely remove the 'sormas_audit_db' - I created a back-up for it, deleted/dropped the db, then restarted the local machine and checked some basic functionalities such as creating a new case, editing a user and user role or changing the language.

The 'sormas_audit_db' was not re-created, the start of the local machine was successful and executing some basic tests was successful.
