### ISSUE TITLE
Measures are displayed in action title column in action view

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#9012]
### Bug Description

Instead of the action title, the measures of an action are displayed in the action title column in the action view.
### Steps to Reproduce

1. Open or create an event
2. Create a new action and fill measures and title fields
3. Check the respective action and the action title column

### Expected Behavior

action title column should display the title
### Screenshots

<img width="360" alt="actionTitleDirectory" src="https://user-images.githubusercontent.com/70317594/165913444-3bef9ef9-136a-43c0-a5bd-7f7f05f7b6f9.PNG">
<img width="855" alt="actionTitleDirectory2" src="https://user-images.githubusercontent.com/70317594/165913449-3603a471-7ed1-45a7-b1d7-777dd2e7afa8.PNG">

### System Details

* Device:
* SORMAS version: 1.70.3 / 1.71-SNAPSHOT
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de / test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by carina29** [comment]
Hello @kwa20 !
I have investigated the bug. The problem is related to one of the comments from this ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4013.  
There is a check in the code when the measure is selected and if is something different than OTHER selected for the measure, the actionMeasure will be displayed instead of the title. 
Since you've said in 4013 that the title should stay, because it's non-compulsory I will remove the check related to the measure. 

Is that ok for you? :)

Thank you very much!

**Comment by mario-kuehne** [comment]
**Bug reproduction**

Reproduced issue with
- Version: 1.70.4 on https://test1401.sormas-oegd.de/
- Version: 1.71.0-SNAPSHOT (f1e438c) on https://test-de2.sormas.netzlink.com/

**Bugfix test**
Will be tested locally because bugfix is not yet deployed on test instances.

**Comment by carina29** [comment]
I have talked with @mario-kuehne that right now with this bugfix the measurements checks were removed and the title is shown in every case.
If we want to have different scenarios based on the selected measurements or given title, I would suggest to open another ticket since in this one it was not requested to handle the combinations mentioned in the above table. 
The only requirement was related to the display of the title instead of the measurement.

**Comment by kwa20** [comment]
@carina29 @mario-kuehne Looks fine to me. I guess the problem here was also related to the hierarchical direction of fallback from measures to title. The fix here should be fine and more intuitive in regards to the column header.

**Comment by AliciaRaber** [comment]
Test performed on test1401.sormas-oegd.de V1.72.1

Created action:
![image](https://user-images.githubusercontent.com/91321821/171645743-41c8b50e-4003-4c44-a716-4988b1f4cd47.png)

Overview in action list:
![image](https://user-images.githubusercontent.com/91321821/171645883-0c6729fe-6be6-4e95-a4a8-bacff4d67fdd.png)

Action title no is displayed according to entry in action.
